name: flask_proj_env
channels:
  - defaults
dependencies:
  - blinker=1.9.0=py310hecd8cb5_0
  - brotlicffi=1.0.9.2=py310h6d0c2b6_1
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.7.15=hecd8cb5_0
  - certifi=2025.8.3=py310hecd8cb5_0
  - cffi=1.17.1=py310h9205ec4_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.2.1=py310hecd8cb5_0
  - expat=2.7.1=h6d0c2b6_0
  - flask=3.1.0=py310hecd8cb5_0
  - icu=73.1=hcec6c5f_0
  - idna=3.7=py310hecd8cb5_0
  - itsdangerous=2.2.0=py310hecd8cb5_0
  - jinja2=3.1.6=py310hecd8cb5_0
  - libabseil=20250127.0=cxx17_h548131f_0
  - libcxx=19.1.7=haebbb44_3
  - libedit=3.1.20230828=h6c40b1e_0
  - libffi=3.4.4=hecd8cb5_1
  - libprotobuf=5.29.3=h66a43dd_1
  - lz4-c=1.9.4=hcec6c5f_1
  - markupsafe=3.0.2=py310h46256e1_0
  - mysql=9.3.0=h7e1d341_3
  - mysql-client=9.3.0=hd6aa1f6_3
  - mysql-common=9.3.0=hee65945_3
  - mysql-connector-python=9.3.0=py310h6d0c2b6_0
  - mysql-devel=9.3.0=hee65945_3
  - mysql-libs=9.3.0=h159e97f_3
  - mysql-server=9.3.0=h8a41abf_3
  - ncurses=6.5=h923df54_0
  - openssl=3.0.17=hee2dfae_0
  - pip=25.3=pyhc872135_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pysocks=1.7.1=py310hecd8cb5_0
  - python=3.10.18=hc958d9f_0
  - readline=8.3=h49f2429_0
  - requests=2.32.4=py310hecd8cb5_0
  - setuptools=78.1.1=py310hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - tk=8.6.15=h3a5a201_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py310hecd8cb5_0
  - werkzeug=3.1.3=py310hecd8cb5_0
  - wheel=0.45.1=py310hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.6=h138b38a_0
